/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    'IconMdi:check': typeof import('~icons/mdi/check')['default']
    'IconMdi:sack': typeof import('~icons/mdi/sack')['default']
    IconMdiAccount: typeof import('~icons/mdi/account')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const 'IconMdi:check': typeof import('~icons/mdi/check')['default']
  const 'IconMdi:sack': typeof import('~icons/mdi/sack')['default']
  const IconMdiAccount: typeof import('~icons/mdi/account')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}